blank_issues_enabled: true
contact_links:
    - name: GitHub Discussions
      url: https://github.com/WhackDevelopment/.../discussions
      about: Start a discussion
    - name: Discord support server
      url: https://discord.gg/kGgMqCf29m
      about: The best place to go for help installing or using WhackDevelopment's softwares.
